### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ASemin1988** [soersoft/soerbot#20]
При запуске из командной строки на Windows 10x64-bit

C:\SoerBot>php run.php
'wmic' is not recognized as an internal or external command,
operable program or batch file.
PHP Fatal error:  Uncaught InvalidArgumentException: Unable to resolve command path in C:\SoerBot\vendor\charlottedunois\livia\src\CommandRegistry.php:621
Stack trace:
#0 C:\SoerBot\vendor\charlottedunois\livia\src\CommandRegistry.php(671): CharlotteDunois\Livia\CommandRegistry->resolveCommandPath('C', '\\SoerBot\\src/.....')
#1 C:\SoerBot\vendor\charlottedunois\livia\src\CommandRegistry.php(299): CharlotteDunois\Livia\CommandRegistry->handleCommandSpacing('C:\\SoerBot\\src/...')
#2 C:\SoerBot\src\Runner.php(77): CharlotteDunois\Livia\CommandRegistry->registerCommand('C:\\SoerBot\\src/...', 'C:\\SoerBot\\src/...', 'C:\\SoerBot\\src/...', 'C:\\SoerBot\\src/...', 'C:\\SoerBot\\src/...', 'C:\\SoerBot\\src/...', 'C:\\SoerBot\\src/...')
#3 C:\SoerBot\src\Runner.php(44): SoerBot\Runner->settings()
#4 C:\SoerBot\run.php(5): SoerBot\Runner->execute()
#5 {main}
  thrown in C:\SoerBot\vendor\charlottedunois\livia\src\CommandRegistry.php on line 621

**Comment by soersoft** [comment]
Проблема решена, ожидается информация об устранении

**Comment by vakhov** [comment]
Проблема в формировании пути. Решилась указание относительного пути до каталога с командами. После правки, пытаясь запустить php run.php, сразу наткнулся на другую ошибку
```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\Users\alex\git_project\soerbot\vendor\guzzlehttp\guzzle\sr
c\Handler\CurlFactory.php:186
Stack trace:
#0 C:\Users\alex\git_project\soerbot\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\Users\alex\git_project\soerbot\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\Users\alex\git_project\soerbot\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(181): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 C:\Users\alex in C:\Users\alex\git_project\soerbot\vendor\charlottedunois\eventemitter\src\EventEmitterErrorTrait.php on line 51

```
Т.к. php в windows установил без каких либо настроек в php.ini, оказалось для полноценной работы curl с сервером/серверами необходимо наличие сертификатов на машине и указание пути до них в php.ini
Решается переходом по ссылке  из ошибки [http://curl.haxx.se/libcurl/c/libcurl-errors.html](http://curl.haxx.se/libcurl/c/libcurl-errors.html), скачиванием сертификата ([для тех кто не нашел ссылку на страницу с сертификатами](https://curl.haxx.se/docs/caextract.html)), и указание полного пути до него в переменной curl.cainfo (не забыв её раскоментировав). Пример ниже.
![image](https://user-images.githubusercontent.com/2041055/53437019-5b7f2580-3a1e-11e9-8bdc-a652ef4a4e52.png)

**Comment by ASemin1988** [comment]
Спасибо.
