### ISSUE TITLE
ConfigurationFileNotFound 

### ISSUE THREAD

**Issue by MikesoWeb** [soersoft/soerbot#21]
Fatal error: Uncaught SoerBot\Exceptions\ConfigurationFileNotFound in C:\sBot\src\Configurator.php:63
Stack trace:
#0 C:\sBot\src\Configurator.php(51): SoerBot\Configurator::load()
#1 C:\sBot\src\Runner.php(177): SoerBot\Configurator::get('users', NULL)
#2 C:\sBot\src\Runner.php(163): SoerBot\Runner->config('users')
#3 C:\sBot\src\Runner.php(151): SoerBot\Runner->configurationForClient()
#4 C:\sBot\src\Runner.php(31): SoerBot\Runner->makeClient()
#5 C:\sBot\run.php(5): SoerBot\Runner->__construct()
#6 {main}
  thrown in C:\sBot\src\Configurator.php on line 63

Пречитал несколько раз всю переписку в дискорд чате, удалял и добавлял бота и composer 
делал composer install,  в файле Runner убирал для пользователей винды слеш как писали, не получается. Выдает исключение.

**Comment by KustovAA** [comment]
Необходимо добавить в проект файл config.yaml, переменная path указывает на него, а его нет)
решение: создаешь config.yaml, копируешь в него содержимое config.example.yaml

**Comment by soersoft** [comment]
все верно понял. Проблема в том, что у нас это исключение не обрабатывается
предлагаю сделать обработку исключения в момент загрузки и выдавать человекопонятное сообзение, что не найден такой-то файл конфигурации (полный путь к файлу конфигурации)

добавлять config.yaml в репозиторий нельзя.
потому что config 
во-первых содержит sensetive данные (пароли, ключи и т.д.), а во вторых в каждой сборке может быть свой.

непойманное исключение - это дурной тон. Либо нужно убирать исключение, либо его ловить.
Не пойманные исключения допускаются только в библиотеках

**Comment by KustovAA** [comment]
if (!file_exists(self::$path)) {
            throw new ConfigurationFileNotFound('config.yaml is not found, you should create one in root dir, use config.example.yaml as example');
}

такой вариант
