### ISSUE TITLE
Автоматизировать переименование config.example.yaml

### ISSUE THREAD

**Issue by soersoft** [soersoft/soerbot#28]
По поводу автоматического создания config.yaml. У меня добавлено правило в скриптах composer.json, после выполнения composer install на чистой версии проекта запускается секция:
```
"post-install-cmd": [
            "@php -r \"file_exists('config.yaml') || copy('config.example.yaml', 'config.yaml');\""
        ],
```

Сейчас он не отрабатывает, т.к. отсутствует файл composer.lock (composer  запускает скрипт в случае, если файл присутствует). Надо подобрать правильное правило, которое отработает после composer install независимо от наличия composer.lock

DOD

**Comment by mlavrik** [comment]
Есть какие-то причины исключать composer.lock из репозитория? В документации composer рекомендуют все же [коммитить его](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control). Мне кажется вполне разумным чтобы у всех были одинаковые версии зависимостей.

**Comment by bonzaza** [comment]
Единственный момент, что если все таки будет принято решение composer.lock сохранять в репозитории, то надо не забыть поменять это правило обратно :)
