### ISSUE TITLE
Команда  $karma (этап 1, сложность: easy)

### ISSUE THREAD

**Issue by soersoft** [soersoft/soerbot#33]
Команда $karma должна:

1. Должна делать emit запрос emit('karma', [username]);
2. выводить результат emit запроса "Ваша карма: [количество очков кармы]"

DoD:

* тест
* команда
* Результат:  "Ваша карма: [количество очков кармы]"

**Comment by bonzaza** [comment]
Правильно понимаю, что emitter 'karma' еще не написан и его написание не входит в это задание?

**Comment by soersoft** [comment]
Здесь будет переделан сам подход раздачи заданий. Я хотел сделать максимально подробно, но тогда по сути я сам делаю декомпозицию задания и навязываю свое мнение. Поэтому ориентироваться на данное Issue особо не надо. Но emit еще не сделан. И здесь надо будет использовать deffered объект. А не только emit.

**Comment by bonzaza** [comment]
Я к тому, что полез в karma компонент и там уже висит свой обработчик, который инкрементирует карму (правда не разобрался по какому событию, но не суть). Вопрос в том, что городить данное задание поверх уже существующей команды как-то совсем неверно. И возникает вопрос, делать отдельную команду или все таки допиливать текущую?

Если допиливать текущую, то хотя бы в двух словах было было неплохо узнать что делает $client->emit('RegisterWatcher' и зачем он повешен на команду, хотя по факту внутри никакой команды нет, а есть обработчик.

**Comment by soersoft** [comment]
Сначала для чего:
Watcher нужен чтобы следить за каждым сообщением в чате и добавлять очки каждому кто пишет. Он должен это делать постоянно в фоновом режиме
Теперь почему в $karma
В данном случае инициализация watcher-а происходит в момент инициализации команды, поэтому он генерирует событие о том что новый watcher хочет зарегистрироваться.
Это не правильно. По-хорошему нужно сделать отдельный реестр для watcher-ов и инициализировать их как и команды отдельно.

**Comment by bonzaza** [comment]
Вот и у меня какой-то диссонанс возник, watcher в команде :) А реестром watcher-ов кто-то занимается? может какой-то простенький bootstrap файл прикрутить с ними.
