### ISSUE TITLE
Помощник для участников Devs - команда $devs [topicname]

### ISSUE THREAD

**Issue by soersoft** [soersoft/soerbot#37]
Необходимо реализовать команду которая будет выводить важные топики, которые нужны для работы в проекте devs

**Основные задачи**:
- выводить топик в личные сообщения пользователю, который его создал
- выводить подсказку если топик указан неверно (список топиков)

**Особенности**
- топики храняться в директории ./store  в виде md-файлов, команда должна сканировать эту директорию, находить (*).topic.md и на основе этих файлов формировать список топиков.

**Comment by MikesoWeb** [comment]
Реализована команда $devs

В данном функционале при вводе команды $devs вызывается подсказка:
Укажите топик: how-to-start, beginner. Чтобы узнать о команде $devs наберите  help
При вводе help вызывается файл readme.devs.md, в котором краткое описание команды и функционала, а так же указана версия команды.

При вводе команды $devs how-to-start выводится в личное сообщение, вызывающего команду информация для новичков о проекте и как начать.

При вводе команды $devs beginner так же в личном сообщении приходит ответ с информацией, например о ссылках, нужных по работе с проектом.

Топики хранятся в папке ./store в виде *.md файлов, создал скрипт который перебирает все файлы в папке и выводит из списком (foreach) - пока не до конца реализовано, но работает на макете.

Вроде решили что вывод списка топиков будет осуществляться командой $devs list

Если топик указан не верно планируется вывод списка топиков (например основных) или переключение на List со списком всех доступных топиков.

Далее тесты, проверки, реализация.

ver.0.0.1
