### ISSUE TITLE
Загрузка топика должна делаться из файла [name].topic.md

### ISSUE THREAD

**Issue by soersoft** [soersoft/soerbot#66]
**Описание фичи**
Команда $devs [name] должна отображать содержимое ./topics/[name].topic.md если такого файла нет, то выводить стандартную подсказку о запуске команды $devs list

Story: #37

**Comment by MikesoWeb** [comment]
В первой версии команды были реализованы данные фичи. Сейчас вышлю код, который примитивен, но выполняет заданные функции.  Работает тупо на switch- case

При вводе команды  `$devs` выводится лист `Инфо о команде  help, список всех топиков  list`

Вводим например `list`

Команда отвечает в личку содержимым файла лист, а именно на данный момент:

> **Список топиков**
>
>
> 1. ` help `            - help.topic.md
> 2. ` how-to-start `    - how-to-start.topic.md  (Думаю для этой команды нужен альяс)
> 3. ` beginner `        - begin.topic.md
> 4. ` list `            - list.topic.md  

Далее в личке можно использовать команду по максималу:

$devs help
$devs how-to-start
$devs beginner
$devs list

Если ввели имя топика не верно, выводится подсказка: 

`Инфо о команде $devs help, список всех топиков $devs list`

1. Предлагаю сократить команду $devs how-to-start до $devs how

2. Предлагаю сократить команду $devs beginner до $devs begin

Сейчас сделаю коммит по этому заданию, все работает.
