### ISSUE TITLE
Librarian

### ISSUE THREAD

**Issue by DenisGeek** [soersoft/soerbot#67]
**Описание фичи**
Функция библиотекаря:
- Предоставлять описания книг по запросу.
- Вывод: личные сообшения или канал
- [Пример: ссылка](https://discordapp.com/channels/524189783568809984/530933105708630037/555258208051003452)

**Дополнительные условия**
- возможность подключения нескольких источников 
- удаления рекламы пиратского контекста
   - например обрезание картинок книг

**Первая итерация**
- проработать архитектуру
  - менеджер
  - источники
  - интерфес обмена
    - запрос менеджер => источник
    - ответ источник => менеджер
- возможно вести **модуль обмена сообщениями в двух направлениях**
  - Задача отвязаться от php, дать возможность разработки микросервисов
  - Первая итерация: две очереди на центрифуге (обсуждаемо)
    - передача
    - прием
- подключение первого иточника: телеграм канал [progLib](https://web.telegram.org/#/im?p=@progbook) и его дочек
  - определить может ли телеграм бот читать чужие каналы
- определение фильтров 
  - по хештегам
  - по описанию
-  тестовый запрос 
-  тестовый ответ

**Comment by DenisGeek** [comment]
Это выглядит как отдельная фича:
- возможно вести **модуль обиена сообщениями в двух направлениях**
  - Задача отвязаться от php, дать возможность разработки микросервисов
  - Первая итерация: две очереди на центрифуге (обсуждаемо) каждый
    - передача
    - прием

**Comment by soersoft** [comment]
Это тянет на отдельный проект )

**Comment by SpIIIII** [comment]
Это - команда бота? Тоесть ты задаешь команду и название книги а оно тебе инфу?
вроде:
$libr "bite of python"
и оно выдает инфу из дотупных источников?

**Comment by DenisGeek** [comment]
Yep, [this an example in discord channel.](https://discordapp.com/channels/524189783568809984/530933105708630037/555258208051003452)
Yep, first step are done several minutes ago. [Started server issue #76](https://github.com/soersoft/soerbot/issues/76)

While task: read about microservices and docker in your case for python

**Comment by DenisGeek** [comment]
Wrong button, sorry ;-)

**Comment by SpIIIII** [comment]
ok i'll find as much infrmarion as i could in shortest posible time. So i can figure what it is in general and applicable to "discord bot" project. I'm afraid  I'm a bit far for development "in team" and development in general, but i came here for that experiance and i'll try my best )

**Comment by DenisGeek** [comment]
- This feature applicable not only for bot, as long as it will build on small almost not dependents parts it can be connected to different consumers.
 - I as well not a team player)))
    - this attitude I like:
   > but i came here for that experiance and i'll try my best )

**Comment by SpIIIII** [comment]
As far I understand (correct me if I'm wrong) that "Librarian" command will have a realization as ordinary librarian.command.php that will sand http requests to the separate app (which we call microservice). Should that app start from run.php with bot himself?
Sorry if I'm asking questions in a wrong thread and which place is right to send them?
