### ISSUE TITLE
Bot Api: queue of outgoing and incoming data

### ISSUE THREAD

**Issue by DenisGeek** [soersoft/soerbot#68]
**Общее описание**
- Задача отвязаться от PHP, дать возможность разработки микросервисов
- Первая итерация: две очереди на центрифуге (обсуждаемо) 
  - передача
  - прием

**Важность**
**Высокая**/Средняя/Низкая

**Сложность**
**Высокая**/Средняя/Низкая

**Comment by DenisGeek** [comment]
Две очереди для событий:
  - исходящие
  - входящие

**Comment by DenisGeek** [comment]
Centrifugo для php:
https://php.ru/forum/threads/centrifugo-dlja-php.68951/

**Comment by DenisGeek** [comment]
Kafka PHP client:
https://www.reddit.com/r/PHP/comments/648zrk/kafka_php_71_library/?utm_medium=android_app&utm_source=share

**Comment by soersoft** [comment]
Зачем центрифуга? Когда можно просто реализовать возможность принять webhooks от рест сервиса?

**Comment by DenisGeek** [comment]
начал разработку 
Первый шаг Story #68 Разработка API в виде UML диаграммы #97

**Comment by DenisGeek** [comment]
PHP get all classes implements interface:
https://stackoverflow.com/questions/3993759/php-how-to-get-a-list-of-classes-that-implement-certain-interface

**Comment by DenisGeek** [comment]
начал разработку
Второй шаг Story #68 Разработка API в виде UML диаграммы #104
