### ISSUE TITLE
Предложения по команде $devs

### ISSUE THREAD

**Issue by bonzaza** [soersoft/soerbot#69]
Столкнувшись с рядом вопросов при написании кода предлагаю следующие топики для команды $devs #37 :
* test - базовые сведения по стилям написания тестов + те обертки, которые дает расширение от Евгения
* codestyle - базовые сведения по стилям написания кода (версия PHP, стандарты PSR-2 или что будет использоваться и где почитать)
* git - базовые сведения по git командам, которые используются на проекте + упоминание веток, какие для чего
* algorithm - базовые сведения по алгоритму работы (https://github.com/soersoft/soerbot/wiki/Алгоритм-работы)

**Comment by DenisGeek** [comment]
Возможно это должно быть подразделом [issue#37 (Помощник для участников Devs - команда $devs ](https://github.com/soersoft/soerbot/issues/37))

**Comment by bonzaza** [comment]
@DenisGeek а не подскажете, как перенести в подраздел?

**Comment by DenisGeek** [comment]
Если это тобой класифицируется как **История**, требующая декомпозиции на задачи то да, иначе если 'то подзадача, то еще и метку сменить, но я не нашел как, также для [issue #67](https://github.com/soersoft/soerbot/issues/67)
