### ISSUE TITLE
Реализовать Web-сервер для приема WebHooks

### ISSUE THREAD

**Issue by soersoft** [soersoft/soerbot#76]
**Общее описание**
Необходимо сделать веб-сервер для приема веб-хуков.

**Важность**
Высокая

**Сложность**
Низкая

**Comment by soersoft** [comment]
Элементарная реализация на ReactPHP:
```
use Psr\Http\Message\ServerRequestInterface;
use React\Http\Response;
use React\Http\Server;

$server = new Server(function (ServerRequestInterface $request) {
            return new Response(
                200,
                array(
                    'Content-Type' => 'text/plain'
                ),
                "Hello world\n"
            );
        });
        $socket = new \React\Socket\Server(isset($argv[1]) ? $argv[1] : '0.0.0.0:0', $this->loop);
        $server->listen($socket);
        echo 'Listening on ' . str_replace('tcp:', 'http:', $socket->getAddress()) . PHP_EOL;
```

Можно в Runner добавить метод  HttpWebHookServer() который будет стартовать сервер.

**Comment by DenisGeek** [comment]
I'm taking this task

**Comment by soersoft** [comment]
Круто!

**Comment by DenisGeek** [comment]
from: [reactphp/react/wiki/FAQ](https://github.com/reactphp/react/wiki/FAQ)
- [React/Stomp](https://github.com/friends-of-reactphp/stomp): Allows you to connect to a message broker, such as [RabbitMQ](https://ru.wikipedia.org/wiki/RabbitMQ) or Apollo.

After while can screw it ))

**Comment by DenisGeek** [comment]
Server has started, response received. [#84 ](https://github.com/DenisGeek/soerbot/commit/cfd85183962910adfca220beaf4213760265d88b)
Takes time for read more about message brokers, and creating API Architecture.
Open for suggestions
