### ISSUE TITLE
Bug: В команде leaderboard-add сбой при пустом файле

### ISSUE THREAD

**Issue by soersoft** [soersoft/soerbot#88]
1. Если нет файла leaderboard.json - выпадаем в ошибку, что файл не найден. 
2. Если создать пустой файл leaderboard.json то при попытке добавить команду:

Fatal error: Uncaught TypeError: Argument 1 passed to CharlotteDunois\Yasmin\Utils\DataHelpers::escapeMarkdown() must be of the type string, null given, called in /Users/sal/github/phptools/discord/bot/vendor/charlottedunois/livia/src/CommandMessage.php on line 347 and defined in /Users/sal/github/phptools/discord/bot/vendor/charlottedunois/yasmin/src/Utils/DataHelpers.php:160
Stack trace:
#0 /Users/sal/github/phptools/discord/bot/vendor/charlottedunois/livia/src/CommandMessage.php(347): CharlotteDunois\Yasmin\Utils\DataHelpers::escapeMarkdown(NULL)
#1 [internal function]: CharlotteDunois\Livia\CommandMessage->CharlotteDunois\Livia\{closure}(NULL)
#2 /Users/sal/github/phptools/discord/bot/vendor/charlottedunois/livia/src/CommandMessage.php(348): array_map(Object(Closure), Array)
#3 /Users/sal/github/phptools/discord/bot/vendor/react/promise/src/Promise.php(81): CharlotteDunois\Livia\CommandMessage->CharlotteDunois\Livia\{closure}(Object(TypeError))
#4 /Users/sal/github/phptools/discord/bot/vendor/react/promise/src/Rejecte in /Users/sal/github/phptools/discord/bot/vendor/charlottedunois/yasmin/src/Utils/DataHelpers.php on line 160

**Comment by ivan-kuznetsov** [comment]
Взял в работу

**Comment by ivan-kuznetsov** [comment]
Пофиксил. Просьба проверить.
